<a href="https://colab.research.google.com/github/tasm3/cs460-data-scienc/blob/hw5/Google_Trends.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Understanding Search Interest with Google Trends

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

# Load Google Trends dataset
trends = pd.read_csv('ai_tools_comparison.csv')

# Inspect the first five rows
trends.head()

         week  chatgpt  gemini  microsoft_copilot
0  2023-08-27       56       3                  1
1  2023-09-03       56       3                  1
2  2023-09-10       63       3                  1
3  2023-09-17       64       3                  1
4  2023-09-24       66       3                  1

In [6]:
# Start coding here
# Use as many cells as you need
trends.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   week               54 non-null     object
 1   chatgpt            54 non-null     int64
 2   gemini             54 non-null     int64
 3   microsoft_copilot  54 non-null     int64
dtypes: int64(3), object(1)
memory usage: 1.8+ KB

In [7]:
trends['week'] = pd.to_datetime(trends['week'])
trends.dtypes

week                 datetime64[ns]
chatgpt                       int64
gemini                        int64
microsoft_copilot             int64
dtype: object